namespace GWANet.Constants
{
    /// <summary>
    /// Region ids, have to be used with corresponding district ids
    /// </summary>
    internal enum RegionIdEnum : short
    {
        America = 0,
        Europe = 2,
        // TODO: Find out the ID for Asia
        International = -2,
    }
    
    /// <summary>
    /// District ids for Europe region
    /// </summary>
    internal enum EuropeDistrictIdEnum : short
    {
        English = 0,
        French = 2,
        German = 3,
        Italian = 4,
        Spanish = 5,
        Polish = 9,
        Russian = 10
    }

    /// <summary>
    /// Provides a constant in game map id of selected region
    /// </summary>
    internal enum MapIdEnum : ushort
    {
        None = 0,
        GladiatorsArena,
        Testmap,
        WarriorsIsleoutpost,
        HuntersIsleoutpost,
        WizardsIsleoutpost,
        WarriorsIsle,
        HuntersIsle,
        WizardsIsle,
        BloodstoneFen,
        TheWilds,
        AuroraGlade,
        DiessaLowlands,
        GatesofKryta,
        DAlessioSeaboard,
        DivinityCoast,
        TalmarkWilderness,
        TheBlackCurtain,
        SanctumCay,
        DroknarsForgeoutpost,
        TheFrostGate,
        IceCavesofSorrow,
        ThunderheadKeep,
        IronMinesofMoladune,
        BorlisPass,
        TalusChute,
        GriffonsMouth,
        TheGreatNorthernWall,
        FortRanik,
        RuinsofSurmia,
        XaquangSkyway,
        NolaniAcademy,
        OldAscalon,
        TheFissureofWoe,
        EmberLightCampoutpost,
        GrendichCourthouseoutpost,
        GlintsChallengemission,
        AuguryRockoutpost,
        SardelacSanitariumoutpost,
        PikenSquareoutpost,
        SageLands,
        MamnoonLagoon,
        Silverwood,
        EttinsBack,
        ReedBog,
        TheFalls,
        DryTop,
        TangleRoot,
        HengeofDenravioutpost,
        
        SenjisCorneroutpost = 51,
        BurningIsleoutpost,
        TearsoftheFallen,
        ScoundrelsRise,
        LionsArchoutpost,
        CursedLands,
        BergenHotSpringsoutpost,
        NorthKrytaProvince,
        NeboTerrace,
        MajestysRest,
        TwinSerpentLakes,
        WatchtowerCoast,
        StingrayStrand,
        KessexPeak,
        DAlessioArenamission,
        
        BurningIsle = 67,
        FrozenIsle,
        NomadsIsle,
        DruidsIsle,
        IsleoftheDeadguildhall,
        TheUnderworld,
        RiversideProvince,
        
        TheHallofHeroesarenamission = 75,
        BrokenTowermission,
        HousezuHeltzeroutpost,
        TheCourtyardarenamission,
        UnholyTemplesmission,
        BurialMoundsmission,
        AscalonCityoutpost,
        TombofthePrimevalKings,
        TheVaultmission,
        TheUnderworldarenamission,
        AscalonArena,
        SacredTemplesmission,
        Icedome,
        IronHorseMine,
        AnvilRock,
        LornarsPass,
        SnakeDance,
        TascasDemise,
        SpearheadPeak,
        IceFloe,
        WitmansFolly,
        MineralSprings,
        DreadnoughtsDrift,
        FrozenForest,
        TravelersVale,
        DeldrimorBowl,
        RegentValley,
        TheBreach,
        AscalonFoothills,
        PockmarkFlats,
        DragonsGullet,
        FlameTempleCorridor,
        EasternFrontier,
        TheScar,
        TheAmnoonOasisoutpost,
        DivinersAscent,
        VultureDrifts,
        TheAridSea,
        ProphetsPath,
        SaltFlats,
        SkywardReach,
        DunesofDespair,
        ThirstyRiver,
        ElonaReach,
        AuguryRockmission,
        TheDragonsLair,
        PerditionRock,
        RingofFire,
        AbaddonsMouth,
        HellsPrecipice,
        
        GoldenGatesmission = 126,
        ScarredEarth2,
        TheEternalGrove,
        LutgardisConservatoryoutpost,
        VasburgArmoryoutpost,
        SerenityTempleoutpost,
        IceToothCaveoutpost,
        BeaconsPerchoutpost,
        YaksBendoutpost,
        FrontierGateoutpost,
        Beetletunoutpost,
        FishermensHavenoutpost,
        TempleoftheAges,
        VentarisRefugeoutpost,
        DruidsOverlookoutpost,
        MaguumaStadeoutpost,
        QuarrelFallsoutpost,
        
        GyalaHatchery = 144,
        TheCatacombs,
        LakesideCounty,
        TheNorthlands,
        AscalonCitypresearing,
        AscalonAcademy,
        AscalonAcademyPvPbattlemission,
        AscalonAcademyunk,
        HeroesAudienceoutpost,
        SeekersPassageoutpost,
        DestinysGorgeoutpost,
        CampRankoroutpost,
        TheGraniteCitadeloutpost,
        MarhansGrottooutpost,
        PortSledgeoutpost,
        CopperhammerMinesoutpost,
        GreenHillsCounty,
        WizardsFolly,
        RegentValleypreSearing,
        TheBarradinEstateoutpost,
        AshfordAbbeyoutpost,
        FoiblesFairoutpost,
        FortRanikpreSearingoutpost,
        BurningIslemission,
        DruidsIslemission,
        
        FrozenIslemission = 170,
        WarriorsIslemission,
        HuntersIslemission,
        WizardsIslemission,
        NomadsIslemission,
        IsleoftheDeadguildhallmission,
        FrozenIsleoutpost,
        NomadsIsleoutpost,
        DruidsIsleoutpost,
        IsleoftheDeadguildhalloutpost,
        FortKogamission,
        ShiverpeakArena,
        AmnoonArenamission,
        DeldrimorArenamission,
        TheCragmission,
        
        RandomArenasoutpost = 188,
        TeamArenasoutpost,
        SorrowsFurnace,
        GrenthsFootprint,
        
        Cavalonoutpost = 193,
        KainengCenteroutpost,
        DrazachThicket,
        JayaBluffs,
        ShenzunTunnels,
        Archipelagos,
        MaishangHills,
        MountQinkai,
        MelandrusHope,
        RheasCrater,
        SilentSurf,
        UnwakingWatersmission,
        MorostavTrail,
        DeldrimorWarCampoutpost,
        
        HeroesCryptmission = 208,
        MourningVeilFalls,
        Ferndale,
        PongmeiValley,
        MonasteryOverlook1,
        ZenDaijunoutpostmission,
        MinisterChosEstateoutpostmission,
        VizunahSquaremission,
        NahpuiQuarteroutpostmission,
        TahnnakaiTempleoutpostmission,
        Arborstoneoutpostmission,
        BoreasSeabedoutpostmission,
        SunjiangDistrictoutpostmission,
        FortAspenwoodmission,
        TheEternalGroveoutpostmission,
        TheJadeQuarrymission,
        GyalaHatcheryoutpostmission,
        RaisuPalaceoutpostmission,
        ImperialSanctumoutpostmission,
        UnwakingWaters,
        GrenzFrontiermission,
        
        AmatzBasin = 230,
        
        ShadowsPassage = 232,
        RaisuPalace,
        TheAuriosMines,
        PanjiangPeninsula,
        KinyaProvince,
        HaijuLagoon,
        SunquaVale,
        WajjunBazaar,
        BukdekByway,
        TheUndercity,
        ShingJeaMonasteryoutpost,
        ShingJeaArena,
        Arborstoneexplorable,
        MinisterChosEstateexplorable,
        ZenDaijunexplorable,
        BoreasSeabedexplorable,
        GreatTempleofBalthazaroutpost,
        TsumeiVillageoutpost,
        SeitungHarboroutpost,
        RanMusuGardensoutpost,
        LinnokCourtyard,
        DwaynaVsGrenth,
        
        SunjiangDistrictexplorable = 256,
        
        NahpuiQuarterexplorable = 265,
        UrgozsWarren,
        
        TahnnakaiTempleexplorable = 269,
        
        AltrummRuins = 272,
        ZosShivrosChannel,
        DragonsThroat,
        IsleofWeepingStoneoutpost,
        IsleofJadeoutpost,
        HarvestTempleoutpost,
        BreakerHollowoutpost,
        LeviathanPitsoutpost,
        IsleoftheNameless,
        ZaishenChallengeoutpost,
        ZaishenEliteoutpost,
        MaatuKeepoutpost,
        ZinKuCorridoroutpost,
        MonasteryOverlook2,
        BrauerAcademyoutpost,
        DurheimArchivesoutpost,
        BaiPaasuReachoutpost,
        SeafarersRestoutpost,
        BejunkanPier,
        VizunahSquareLocalQuarteroutpost,
        VizunahSquareForeignQuarteroutpost,
        FortAspenwoodLuxonoutpost,
        FortAspenwoodKurzickoutpost,
        TheJadeQuarryLuxonoutpost,
        TheJadeQuarryKurzickoutpost,
        UnwakingWatersLuxonoutpost,
        UnwakingWatersKurzickoutpost,
        
        EtnaranKeysmission = 300,
        RaisuPavilion,
        KainengDocks,
        TheMarketplaceoutpost,
        
        TheDeep = 307,
        AscalonArenamission,
        Annihilationmission,
        KillCountTrainingmission,
        PriestAnnihilationTraining,
        ObeliskAnnihilationTrainingmission,
        SaoshangTrail,
        ShiverpeakArenamission,
        
        DAlessioArenamission3 = 318,
        AmnoonArenamission3,
        FortKogamission3,
        HeroesCryptmission3,
        ShiverpeakArenamission3,
        
        SaltsprayBeachLuxonoutpost = 328,
        SaltsprayBeachKurzickoutpost,
        HeroesAscentoutpost,
        GrenzFrontierLuxonoutpost,
        GrenzFrontierKurzickoutpost,
        TheAncestralLandsLuxonoutpost,
        TheAncestralLandsKurzickoutpost,
        EtnaranKeysLuxonoutpost,
        EtnaranKeysKurzickoutpost,
        KaanaiCanyonLuxonoutpost,
        KaanaiCanyonKurzickoutpost,
        DAlessioArenamission2,
        AmnoonArenamission2,
        FortKogamission2,
        HeroesCryptmission2,
        ShiverpeakArenamission2,
        TheHallofHeroes,
        TheCourtyard,
        ScarredEarth,
        TheUnderworldPvP,
        TanglewoodCopseoutpost,
        SaintAnjekasShrineoutpost,
        EredonTerraceoutpost,
        DivinePath,
        BrawlersPitmission,
        PetrifiedArenamission,
        SeabedArenamission,
        IsleofWeepingStonemission,
        IsleofJademission,
        ImperialIslemission,
        IsleofMeditationmission,
        ImperialIsleoutpost,
        IsleofMeditationoutpost,
        IsleofWeepingStone,
        IsleofJade,
        ImperialIsle,
        IsleofMeditation,
        
        ShingJeaArenamission = 366,
        
        DragonArena = 368,
        JahaiBluffs,
        Kamadanmission,
        MargaCoast,
        Fahranurmission,
        SunwardMarches,
        
        BarbarousShore = 375,
        CampHojanuoutpost,
        BahdokCaverns,
        WehhanTerracesoutpost,
        DejarinEstate,
        ArkjokWard,
        YohlonHavenoutpost,
        GandaratheMoonFortress,
        
        TheFloodplainofMahnkelon = 384,
        LionsArchSunspearsinKryta,
        TuraisProcession,
        SunspearSanctuaryoutpost,
        AspenwoodGateKurzickoutpost,
        AspenwoodGateLuxonoutpost,
        JadeFlatsKurzickoutpost,
        JadeFlatsLuxonoutpost,
        YatendiCanyons,
        ChantryofSecretsoutpost,
        GardenofSeborhin,
        HoldingsofChokhin,
        MihanuTownshipoutpost,
        VehjinMines,
        BasaltGrottooutpost,
        ForumHighlands,
        KainengCenterSunspearsinCantha,
        
        ResplendentMakuun = 402,
        HonurHilloutpost,
        WildernessofBahdza,
        
        VehtendiValley = 406,
        YahnurMarketoutpost,
        
        TheHiddenCityofAhdashim = 413,
        TheKodashBazaaroutpost,
        LionsGate,
        
        TheMirrorofLyss = 419,
        SecuretheRefuge,
        VentaCemetery,
        KamadanJewelofIstanexplorable,
        TheTribunal,
        KodonurCrossroads,
        RilohnRefuge,
        PogahnPassage,
        ModdokCrevice,
        TiharkOrchard,
        Consulate,
        PlainsofJarin,
        SunspearGreatHalloutpost,
        CliffsofDohjok,
        DzagonurBastion,
        DashaVestibule,
        GrandCourtofSebelkeh,
        CommandPost,
        JokosDomain,
        BonePalaceoutpost,
        TheRupturedHeart,
        TheMouthofTormentoutpost,
        TheShatteredRavines,
        LairoftheForgottenoutpost,
        PoisonedOutcrops,
        TheSulfurousWastes,
        TheEbonyCitadelofMallyxmission,
        TheAlkaliPan,
        ALandofHeroes,
        CrystalOverlook,
        KamadanJewelofIstanoutpost,
        GateofTormentoutpost,
        
        NightfallenGarden = 455,
        ChurrhirFields,
        BeknurHarboroutpost,
        
        TheUnderworld2 = 461,
        HeartofAbaddon,
        TheUnderworld3,
        NightfallenCoast,
        NightfallenJahai,
        DepthsofMadness,
        RollerbeetleRacing,
        DomainofFear,
        GateofFearoutpost,
        DomainofPain,
        BloodstoneFenquest,
        DomainofSecrets,
        GateofSecretsoutpost,
        DomainofAnguish,
        
        OozePitmission = 475,
        JennursHorde,
        NunduBay,
        GateofDesolation,
        ChampionsDawnoutpost,
        RuinsofMorah,
        FahranurTheFirstCity,
        BjoraMarches,
        ZehlonReach,
        LahtendaBog,
        ArborBay,
        IssnurIsles,
        BeknurHarbor,
        MehtaniKeys,
        KodlonuHamletoutpost,
        IslandofShehkah,
        JokanurDiggings,
        BlacktideDen,
        ConsulateDocks,
        GateofPain,
        GateofMadness,
        AbaddonsGate,
        SunspearArena,
        
        IceCliffChasms = 499,
        BokkaAmphitheatre,
        RivenEarth,
        TheAstralariumoutpost,
        ThroneofSecrets,
        ChurranuIslandArenamission,
        ShingJeaMonasterymission,
        HaijuLagoonmission,
        JayaBluffsmission,
        SeitungHarbormission,
        TsumeiVillagemission,
        SeitungHarbormission2,
        TsumeiVillagemission2,
        
        DrakkarLake = 513,
        
        MinisterChosEstatemission2 = 512,
        
        UnchartedIsleoutpost = 529,
        IsleofWurmsoutpost,
        UnchartedIsle,
        IsleofWurms,
        UnchartedIslemission,
        IsleofWurmsmission,
        
        SunspearArenamission = 536,
        CorruptedIsleoutpost,
        IsleofSolitudeoutpost,
        CorruptedIsle,
        IsleofSolitude,
        CorruptedIslemission,
        IsleofSolitudemission,
        SunDocks,
        ChahbekVillage,
        RemainsofSahlahja,
        JagaMoraine,
        Bombardmentmission,
        NorrhartDomains,
        HeroBattlesoutpost,
        TheBeachheadmission,
        TheCrossingmission,
        DesertSandsmission,
        VarajarFells,
        DajkahInlet,
        TheShadowNexus,
        
        SparkflySwamp = 558,
        GateoftheNightfallenLandsoutpost,
        CathedralofFlamesLevel1,
        TheTroubledKeeper,
        
        VerdantCascades = 566,
        CathedralofFlamesLevel2,
        CathedralofFlamesLevel3,
        MagusStones,
        CatacombsofKathandraxLevel1,
        CatacombsofKathandraxLevel2,
        AlcaziaTangle,
        RragarsMenagerieLevel1,
        RragarsMenagerieLevel2,
        RragarsMenagerieLevel3,
        OozePit,
        SlaversExileLevel1,
        OolasLabLevel1,
        OolasLabLevel2,
        OolasLabLevel3,
        ShardsofOrrLevel1,
        ShardsofOrrLevel2,
        ShardsofOrrLevel3,
        ArachnisHauntLevel1,
        ArachnisHauntLevel2,
        
        FetidRivermission = 593,
        
        ForgottenShrinesmission = 596,
        
        Antechambermission = 598,
        
        VloxenExcavationsLevel1 = 604,
        VloxenExcavationsLevel2,
        VloxenExcavationsLevel3,
        HeartoftheShiverpeaksLevel1,
        HeartoftheShiverpeaksLevel2,
        HeartoftheShiverpeaksLevel3,
        
        BloodstoneCavesLevel1 = 612,
        BloodstoneCavesLevel2,
        BloodstoneCavesLevel3,
        BogrootGrowthsLevel1,
        BogrootGrowthsLevel2,
        RavensPointLevel1,
        RavensPointLevel2,
        RavensPointLevel3,
        SlaversExileLevel2,
        SlaversExileLevel3,
        SlaversExileLevel4,
        SlaversExileLevel5,
        VloxsFalls,
        BattledepthsLevel1,
        BattledepthsLevel2,
        BattledepthsLevel3,
        SepulchreofDragrimmarLevel1,
        SepulchreofDragrimmarLevel2,
        FrostmawsBurrowsLevel1,
        FrostmawsBurrowsLevel2,
        FrostmawsBurrowsLevel3,
        FrostmawsBurrowsLevel4,
        FrostmawsBurrowsLevel5,
        DarkrimeDelvesLevel1,
        DarkrimeDelvesLevel2,
        DarkrimeDelvesLevel3,
        GaddsEncampmentoutpost,
        UmbralGrottooutpost,
        RataSumoutpost,
        TarnishedHavenoutpost,
        EyeoftheNorthoutpost,
        Sifhallaoutpost,
        GunnarsHoldoutpost,
        Olafsteadoutpost,
        HallofMonuments,
        DaladaUplands,
        DoomloreShrineoutpost,
        GrothmarWardowns,
        LongeyesLedgeoutpost,
        SacnothValley,
        CentralTransferChamberoutpost,
        CurseoftheNornbear,
        BloodWashesBlood,
        AGateTooFarLevel1,
        AGateTooFarLevel2,
        AGateTooFarLevel3,
        TheElusiveGolemancerLevel1,
        TheElusiveGolemancerLevel2,
        TheElusiveGolemancerLevel3,
        FindingtheBloodstoneLevel1,
        FindingtheBloodstoneLevel2,
        FindingtheBloodstoneLevel3,
        GeniusOperatedLivingEnchantedManifestation,
        AgainsttheCharr,
        WarbandofBrothersLevel1,
        WarbandofBrothersLevel2,
        WarbandofBrothersLevel3,
        AssaultontheStronghold,
        DestructionsDepthsLevel1,
        DestructionsDepthsLevel2,
        DestructionsDepthsLevel3,
        ATimeforHeroes,
        WarbandTraining,
        BorealStationoutpost,
        CatacombsofKathandraxLevel3,
        
        AttackoftheNornbear = 678,
        CinematicCaveNornCursed,
        CinematicSteppeInterrogation,
        CinematicInteriorResearch,
        CinematicEyeVisionA,
        CinematicEyeVisionB,
        CinematicEyeVisionC,
        CinematicEyeVisionD,
        PolymockColiseum,
        PolymockGlacier,
        PolymockCrossing,
        CinematicMountainResolution,
        ColdasIce,
        BeneathLionsArch,
        TunnelsBelowCantha,
        CavernsBelowKamadan,
        CinematicMountainDwarfs,
        ServiceInDefenseoftheEye,
        ManoaNorno,
        ServicePracticeDummy,
        HeroTutorial,
        
        TheNornFightingTournament = 700,
        SecretLairoftheSnowmen,
        NornBrawlingChampionship,
        KilroysPunchoutTraining,
        FronisIrontoesLairmission,
        TheJusticiarsEnd,
        
        TheGreatNornAlemoot = 707,
        Epilogue = 710,
        InsidiousRemnants,
        
        AttackonJalissCamp = 717,
        
        CostumeBrawloutpost = 721,
        WhitefuryRapidsmission,
        KystenShoremission,
        DeepwayRuinsmission,
        PlikkupWorksmission,
        KilroysPunchoutTournament,
        SpecialOpsFlameTempleCorridor,
        SpecialOpsDragonsGullet,
        SpecialOpsGrendichCourthouse,
        TheTenguAccords,
        TheBattleofJahai,
        TheFlightNorth,
        TheRiseoftheWhiteMantle,
        
        FindingtheBloodstonemission = 759,
        GeniusOperatedLivingEnchantedManifestationmission,
        AgainsttheCharrmission,
        Warbandofbrothersmission,
        AssaultontheStrongholdmission,
        DestructionsDepthsmission,
        ATimeforHeroesmission,
        CurseoftheNornbearmission,
        BloodWashesBloodmission,
        AGateTooFarmission,
        TheElusiveGolemancermission,
        
        SecretLairoftheSnowmen2 = 781,
        SecretLairoftheSnowmen3,
        DroknarsForgecinematic,
        IsleoftheNamelessPvP,
        
        TempleoftheAgesRox = 788,
        WajjunBazaarPox,
        BokkaAmphitheatreNox,
        SecretUndergroundLair,
        GolemTutorialSimulation,
        SnowballDominance,
        ZaishenMenagerieGrounds,
        ZaishenMenagerieoutpost,
        CodexArenaoutpost,
        TheUnderworldSomethingWickedThisWayComes,
        TheUnderworldDontFeartheReapers,
        LionsArchHalloweenoutpost,
        LionsArchWintersdayoutpost,
        LionsArchCanthanNewYearoutpost,
        AscalonCityWintersdayoutpost,
        DroknarsForgeHalloweenoutpost,
        DroknarsForgeWintersdayoutpost,
        TombofthePrimevalKingsHalloweenoutpost,
        ShingJeaMonasteryDragonFestivaloutpost,
        ShingJeaMonasteryCanthanNewYearoutpost,
        
        KamadanJewelofIstanHalloweenoutpost = 818,
        KamadanJewelofIstanWintersdayoutpost,
        KamadanJewelofIstanCanthanNewYearoutpost,
        EyeoftheNorthoutpostWintersdayoutpost,
        
        WarinKrytaTalmarkWilderness = 837,
        WarinKrytaTrialofZinn,
        WarinKrytaDivinityCoast,
        WarinKrytaLionsArchKeep,
        WarinKrytaDAlessioSeaboard,
        WarinKrytaTheBattleforLionsArch,
        WarinKrytaLionsArch,
        WarinKrytaTheMausoleum,
        WarinKrytaRise,
        WarinKrytaShadowsintheJungle,
        WarinKrytaAVengeanceofBlades,
        WarinKrytaAuspiciousBeginnings,
        
        Olafsteadcinematic = 854,
        TheGreatSnowballFightoftheGodsOperationCrushSpirits,
        TheGreatSnowballFightoftheGodsFightinginaWinterWonderland,
        EmbarkBeach,
        
        DragonsThroatareaWhatWaitsinShadow = 860,
        KainengCenterWindsofChangeAChanceEncounter,
        TheMarketplaceareaTrackingtheCorruption,
        BukdekBywayWindsofChangeCanthaCourierCrisis,
        TsumeiVillageWindsofChangeATreatysaTreaty,
        SeitungHarborareaDeadlyCargo,
        TahnnakaiTempleWindsofChangeTheRescueAttempt,
        WajjunBazaarWindsofChangeViolenceintheStreets,
        ScarredPsychemission,
        ShadowsPassageWindsofChangeCallingAllThugs,
        AltrummRuinsFindingJinnai,
        ShingJeaMonasteryRaidonShingJeaMonastery,
        KainengCenterWindsofChangeRaidonKainengCenter,
        WajjunBazaarWindsofChangeMinistryofOppression,
        TheFinalConfrontation,
        LakesideCounty1070Ae,
        AshfordCatacombs1070Ae,
    }
}